### ISSUE TITLE
lost tokens

### ISSUE THREAD

**Issue by Captainherb** [tronscan/tronscan-frontend#1030]
I transferred 95 IGG and 74 EOY and 91,958 TWEET from my GuildChat wallet to my Tronscan wallet today but they never arrived.  This is not the first time I have lost tokens during transfer to Tronscan.  What gives?

**Comment by nskendrovic** [comment]
I am missing 21 000 TRX. I placed order on tronscan and it was not there. Now the DEX is not even showing trc20 token anymore.
I subbmited formal feedback 3 days ago and nothing.
That is 500$ down the train due to technology that isnt working.
And they are promoting it on niTRON...lol what a joke. they cant handle what they have now.
