### ISSUE TITLE
no open wallet to view

### ISSUE THREAD

**Issue by denniswatts62** [tronscan/tronscan-frontend#1103]
when i hook my ledger nano s up to tronscan it showing no wallet to view! ive transferred all 26,532 coins onto this site onto my ledger, and now it seems, that the wallet has just disappeared! how is this happening?i need answers,are you saying ive lost all my trx on tronscan?

**Comment by Rovak** [comment]
are you using the desktop or web version? please use https://tronscan.org

**Comment by denniswatts62** [comment]
Im so sorry i was freakimg out.I googled tronscan and found it there not on the downloaded trond desktop

Sent from Yahoo Mail on Android 
 
  On Sat, Feb 16, 2019 at 5:30 AM, Roy van Kaathoven<notifications@github.com> wrote:   
are you using the desktop or web version? please use https://tronscan.org

**Comment by VPIRELLI23** [comment]
I am having the same issue. Are there any solutions?

**Comment by VPIRELLI23** [comment]
I will try that... Thanks! Freaking out as well! Lol

**Comment by denniswatts62** [comment]
Yes!I found my coins.there are two tronscans.one is the one you download onto your desktop or laptop.the other you can just google.I googled tronscan and the site showed up and there was all my coins plus the btt airdrop.

Sent from Yahoo Mail on Android 
 
  On Sat, Feb 16, 2019 at 6:21 AM, VPIRELLI23<notifications@github.com> wrote:   
I am having the same issue. Are there any solutions?

**Comment by VPIRELLI23** [comment]
Man, I really thank you for your help!

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by denniswatts62** [comment]
No problem.I was on my own finding this out also.because I could of swore I did all my transactions from my desktop tronscan downloaded site. Iwn alot of xrp ada and trx all will do well

Sent from Yahoo Mail on Android 
 
  On Sat, Feb 16, 2019 at 8:50 PM, VPIRELLI23<notifications@github.com> wrote:   Man, I really thank you for your help!

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by VPIRELLI23** [comment]
Yes Sir! I'm bullish on Xrp Trx Holochain Pundi Siacoin BTT and Vechain.

On Sat, Feb 16, 2019, 12:47 PM denniswatts62 <notifications@github.com<mailto:notifications@github.com> wrote:
No problem.I was on my own finding this out also.because I could of swore I did all my transactions from my desktop tronscan downloaded site. Iwn alot of xrp ada and trx all will do well

Sent from Yahoo Mail on Android

On Sat, Feb 16, 2019 at 8:50 PM, VPIRELLI23<notifications@github.com<mailto:notifications@github.com>> wrote: Man, I really thank you for your help!

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by denniswatts62** [comment]
You need ada cardano also


Sent from Yahoo Mail on Android 
 
  On Sun, Feb 17, 2019 at 7:12 AM, VPIRELLI23<notifications@github.com> wrote:   Yes Sir! I'm bullish on Xrp Trx Holochain Pundi Siacoin BTT and Vechain.

On Sat, Feb 16, 2019, 12:47 PM denniswatts62 <notifications@github.com<mailto:notifications@github.com> wrote:
No problem.I was on my own finding this out also.because I could of swore I did all my transactions from my desktop tronscan downloaded site. Iwn alot of xrp ada and trx all will do well

Sent from Yahoo Mail on Android

On Sat, Feb 16, 2019 at 8:50 PM, VPIRELLI23<notifications@github.com<mailto:notifications@github.com>> wrote: Man, I really thank you for your help!

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by VPIRELLI23** [comment]
Ok
I'll give it another look. Been watching the Digital Asset Investor on YouTube and he gave a good review on ada.

On Feb 17, 2019 8:45 AM, denniswatts62 <notifications@github.com> wrote:
You need ada cardano also


Sent from Yahoo Mail on Android

On Sun, Feb 17, 2019 at 7:12 AM, VPIRELLI23<notifications@github.com> wrote: Yes Sir! I'm bullish on Xrp Trx Holochain Pundi Siacoin BTT and Vechain.

On Sat, Feb 16, 2019, 12:47 PM denniswatts62 <notifications@github.com<mailto:notifications@github.com> wrote:
No problem.I was on my own finding this out also.because I could of swore I did all my transactions from my desktop tronscan downloaded site. Iwn alot of xrp ada and trx all will do well

Sent from Yahoo Mail on Android

On Sat, Feb 16, 2019 at 8:50 PM, VPIRELLI23<notifications@github.com<mailto:notifications@github.com>> wrote: Man, I really thank you for your help!

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by denniswatts62** [comment]
DAI is very knowledgeable on XRP and crypto currency's since he has worked in that area in his past, He keeps me motivated,His top 3 were XRP,TRX and ADA

    On ‎Sunday‎, ‎February‎ ‎17‎, ‎2019‎ ‎10‎:‎53‎:‎17‎ ‎PM‎ ‎+03, VPIRELLI23 <notifications@github.com> wrote:  
 
 Ok
I'll give it another look. Been watching the Digital Asset Investor on YouTube and he gave a good review on ada.

On Feb 17, 2019 8:45 AM, denniswatts62 <notifications@github.com> wrote:
You need ada cardano also


Sent from Yahoo Mail on Android

On Sun, Feb 17, 2019 at 7:12 AM, VPIRELLI23<notifications@github.com> wrote: Yes Sir! I'm bullish on Xrp Trx Holochain Pundi Siacoin BTT and Vechain.

On Sat, Feb 16, 2019, 12:47 PM denniswatts62 <notifications@github.com<mailto:notifications@github.com> wrote:
No problem.I was on my own finding this out also.because I could of swore I did all my transactions from my desktop tronscan downloaded site. Iwn alot of xrp ada and trx all will do well

Sent from Yahoo Mail on Android

On Sat, Feb 16, 2019 at 8:50 PM, VPIRELLI23<notifications@github.com<mailto:notifications@github.com>> wrote: Man, I really thank you for your help!

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________
