### ISSUE TITLE
lost all TRX after unfreezed

### ISSUE THREAD

**Issue by soloveyalexander** [tronscan/tronscan-frontend#1106]
I had frozen 35993 TRX and 1000 TRX
I also had  9.5 TRX on my balance.
After I unfrized all the TRX, I got an error that the time for unfreezing had not come.
I went out of my wallet for about an hour, after I entered, I discovered that after unfreezing all my TRX went to this address
TBq5kamBLkehUmmmh8sizrsuu2QNBvsRfC

Tell me what I did wrong, and is there a chance to get my TRX back?

**Comment by robballonoff** [comment]
did you get a response? I had a similar problem and have no clue what to do

**Comment by soloveyalexander** [comment]
Hi.I think that I lost trx forever. Also I have no answer from support.
In transactions i see that all trx sent into some address. Also I used trx
wallet for desktop and I think that it has malware and it stole my private
key. Are you used at least 1 time trx desktop wallet?
(my english is not good im can speak on russian or ukrainian if you want. )

чт, 21 февр. 2019 г. в 07:38, robballonoff <notifications@github.com>:

**Comment by soloveyalexander** [comment]
Also i saw this post about tron desktop wallet( use google translate if
needed )
https://crypto.kg/threads/servis-tronscan-dlja-windows-na-dannyj-moment-neset-opasnost-dlja-polzovatelja.3571/

пт, 22 февр. 2019 г. в 18:02, Александр Соловьёв <solovey.alex.as@gmail.com

**Comment by robballonoff** [comment]
Thanks for the response. It seems that my problem was related to using the tronscan address that included GitHub. When I went directly through tronscan. Org and then try to sign into my ledger it worked fine. Not sure I understand why, because in the past I was able to login the other way and it worked fine. This all seems more confusing than it should be for Mass adoption...Sent via the Samsung GALAXY S® 5, an AT&T 4G LTE smartphone

-------- Original message --------

**Comment by robballonoff** [comment]
I was actually using the tronscan. Org wallet through GitHub. I use my ledger which obviously saves the private keys separately. So, After figuring out I was logging into the wrong site somehow... I got my situation corrected.Sent via the Samsung GALAXY S® 5, an AT&T 4G LTE smartphone

-------- Original message --------
