### ISSUE TITLE
tronscan won't freeze trx 

### ISSUE THREAD

**Issue by Kowai** [tronscan/tronscan-frontend#1114]
I tryed many times during the last few hours. Any reasons ?

**Comment by Rovak** [comment]
Please provide more details, are you using the desktop client, which browser, ledger, private key, etc.. thanks

**Comment by Kowai** [comment]
It was the website directly with the browser saved private key that is always in. 
This morning it worked.

**Comment by tritonlc** [comment]
Hi I’m having exactly the same issue. I cannot longer freeze any Tron while using nano ledger with Chrome browser. I get a please confirm transaction in my nano ledger s, I click on confirm transaction and Tron scan says that the tokens have been successfully frozen but the transaction is not being sent to the blockchain, because if I check in Tron scan under transaction history, the transaction is not listed and tokens are still unfrozen. Tried several times, closing browser, restarting nano ledger etc to no avail. This was working before but it suddenly stopped working.

**Comment by Rovak** [comment]
This is an issue with the latest version of chrome https://support.ledger.com/hc/en-us/articles/360018810413-U2F-timeout-in-Chrome-browser

Use opera until Chrome publishes a fix
