### ISSUE TITLE
No deposit of coins

### ISSUE THREAD

**Issue by Jhurle04** [tronscan/tronscan-frontend#119]
I did the "request to test" to receive 10,000 TRX, however it has not yet arrived in my account, but when i try and repeat it, it says i've exceeded the limit of requests.  When will the Tron be available?

**Comment by Jhurle04** [comment]
Not acceptable, Tron should arrive correct?  Pleas confirm and do NOT close
THIS TICKET!

Regards,
Jack

**Comment by Rovak** [comment]
Hi @Jhurle04, i'm closing this ticket because there are multiple tickets for the exact same issue. The problem is that bots are requesting all the TRX and the account can no longer distribute the TRX. I'm working on a solution at https://github.com/tronscan/tronscan-frontend/pull/150 which will be deployed tomorrow.

When the recaptcha is deployed the TRX account will be refilled and you should be able to request TRX again.

I'm sorry for the inconvenience.

**Comment by Jhurle04** [comment]
There are multiple tickets because it's a huge problem.  I will look to
request it tomorrow, and will email you when completed.  Thank you.
