### ISSUE TITLE
Can someone please guide me to the group that deal with the tronscan web wallet?

### ISSUE THREAD

**Issue by bungfut** [tronscan/tronscan-frontend#1519]
Can someone please guide me to the group that deal with the tronscan web wallet?

_Originally posted by @poppytroxell in https://github.com/tronscan/tronscan-frontend/issues/1504#issuecomment-764218807_

**Comment by poppytroxell** [comment]
Hello, you contacted the right group github, but they are so backed up ever since covid and not answering many questions.Your best bet is join telegram chat group.The have two great groups you should join.I got most of my info there and from youtube.Tronlink official groupTronscan.org official groupOn May 29, 2021 2:41 AM, Bungfut ***@***.***> wrote:
Can someone please guide me to the group that deal with the tronscan web wallet?
Originally posted by @poppytroxell in #1504 (comment)

**Comment by bbsyaya** [comment]
> Can someone please guide me to the group that deal with the tronscan web wallet?
> 
> _Originally posted by @poppytroxell in [#1504 (comment)](https://github.com/tronscan/tronscan-frontend/issues/1504#issuecomment-764218807)_

you can join https://t.me/tronscan_org and
