### ISSUE TITLE
Suggestion: Voting page sort from low to high for better visibility of candidates

### ISSUE THREAD

**Issue by Huaxan** [tronscan/tronscan-frontend#362]
I have this feeling people tend to vote for the ones that already have been elected and fail to scroll past those GR's.

I would suggest when you start voting to sort the candidates from low to high instead the current high to low, this would get some visibility to the unknown or new SR candidates

**Comment by joe-meyer** [comment]
I think this is a very subjective/opinionated thing. I think the best option would be to just make the columns sortable so that people could get a view of gains over 24/6 hours or sort by the number of votes in ascending or descending order as they see fit.

That said my personal opinion is that the current sorting is fine. Odds are if they're at the top they are there for a reason and by putting those people at the bottom you're forcing the majority of people to scroll to see the people they voted for. Just my $0.02 though.
