### ISSUE TITLE
Proposal: Keep Wallet Signed In On Page Refresh or New Browser Tab

### ISSUE THREAD

**Issue by joe-meyer** [tronscan/tronscan-frontend#395]
There are several issues that have been logged (#366, #329, #271) due to the wallet information only persisting for the duration the user remains on the page. When the user refreshes the page via the refresh button they are automatically logged out of the wallet. Additionally, today you could potentially have multiple wallets open in different tabs and that might become confusing.

I think that it makes sense to avoid using cookies that might end up sending data to/from the web server, potentially creating a security hole, additionally GDPR makes using cookies a hassle so one more reason to avoid them.

Instead, perhaps we could leverage `window.localStorage` (https://developer.mozilla.org/en-US/docs/Web/API/Window/localStorage). It seems compatible with most modern browsers, and it would allow us to keep the information only on the user's PC.

I'd propose that we save the necessary wallet info here so that if a user refreshes the page or opens tronscan.org in the same browser, they remain signed in with the currently active account. I think keeping the user logged in for 1 hours would be a good starting point at least.

@Rovak do you have any opinions on this approach?

**Comment by Rovak** [comment]
In a previous version the private keys were stored in localStorage. I removed this because some users were concerned that by placing the private key in localStorage that the private key will be available in plain text format on the system and could be read by malicious programs.

I agree that this is an issue and before localStorage is enabled there should be a way to persist the private key in a encrypted format. There is no way to enforce the 1 hour expiration if the user never visits Tronscan again. So the key could be stuck on the system for years.

I propose to encrypt the private key with AES using the same password that the user inputs during the create wallet wizard. When the user visits tronscan again they can see their (locked) wallet. Whenever they want to make a transaction they will have to unlock the wallet with the password.
