### ISSUE TITLE
Scam Tokens Do Nothing To Help The Tron Community 

### ISSUE THREAD

**Issue by eatroots** [tronscan/tronscan-frontend#584]
I looked into a token called TON tonlab.io it's a scam. I contacted the people they are impersonating as developers and advisers they confirmed its a scam.  I love Tron....but can you please come up with a vetting process for tokens.  Not good investors who believe in Tron getting scammed.

**Comment by Tadlo1** [comment]
This is bad. I participated in Tronchat and I think I been scammed too because they have not confirmed that it is them on the participating section. There needs to be some kind of barrier too doing this or it will eventually tarnish Tron from gaining new users, when stories start coming out of their own community falling victim.
