### ISSUE TITLE
Shouldn't the user be able to unfreeze a proportion of their TRX rather than all?

### ISSUE THREAD

**Issue by OneCoinWillRuleThemAllTRX** [tronscan/tronscan-frontend#620]
Shouldn't the user be able to unfreeze a proportion of their TRX

If I have a total balance of 3000 and I freeze 1000 frozen on 1st Jan then freeze 2000 on 2nd of Jan then I should have two lots of TRX frozen and on differing expiry dates.

Subsequently if I decided to unfreeze my TRX shouldn't I be able to unfreeze 500 and leave the rest frozen?

At the moment I think the system automatically extends the expiry date of ALL frozen TRX if you decide to freeze additional TRX.

![image](https://user-images.githubusercontent.com/42871282/45413178-73c9d680-b670-11e8-972a-3ec7b6119a06.png)

**Comment by dbriggsie** [comment]
This would cause an extra issue, because if you voted multiple SR's (for example more than 3).
Then when unfreezing X amount, it could unfreeze on an SR you didn't want to remove your votes from.

**Comment by OneCoinWillRuleThemAllTRX** [comment]
How about allow the feature of unfreezing a certain amount for those who only for for 1 or 2 SRs?  

So if you only voted for 1 or 2 SR and you click on unfreeze it will give you the option to unfreeze a certain amount.  The reason for this is that bandwidth is accrued when you freeze all of your TRX but when it unfreezes (all of them) you lost that bandwidth.  It would be great if users had the option to unfreeze a proportion and be able to use the bandwidth for transactions if they chose to.

Additionally if you took at look at the stats I'd wager that most people would only vote for 1 SR maybe 2?

**Comment by chuckyloco** [comment]
any one know why i can't unfreeze my frozen trx?? the link to voting isn' t opening for me is that because i use explorer?

**Comment by Tadlo1** [comment]
You can technically unfreeze by going too vote and pressing the minus button next to the SR you wish to reduce the vote on. 

Done this by accident other day.

Hope this helps

**Comment by chuckyloco** [comment]
Hi,
Well the problem is when i press on the vote button the new window to the voting isn't loading its stays blanc.
So the links under the buttons aren't working.
So i can't do anything.

Greetz

Chuckyloco



Verzonden vanaf mijn Samsung Galaxy-smartphone.

-------- Oorspronkelijk bericht --------
Van: Tadlo1 <notifications@github.com>
Datum: 18-09-18 17:17 (GMT+01:00)
Aan: tronscan/tronscan-frontend <tronscan-frontend@noreply.github.com>
Cc: chuckyloco <mpdeclerck@live.nl>, Comment <comment@noreply.github.com>
Onderwerp: Re: [tronscan/tronscan-frontend] Shouldn't the user be able to unfreeze a proportion of their TRX rather than all? (#620)


You can technically unfreeze by going too vote and pressing the minus button next to the SR you wish to reduce the vote on.

Done this by accident other day.

Hope this helps
