### ISSUE TITLE
Zero tron Power — With A TRX Balance. Unable to Unfreeze/Vote/Freeze

### ISSUE THREAD

**Issue by JWhiteUX** [tronscan/tronscan-frontend#782]
Not sure if this is related to this … https://github.com/tronscan/tronscan-frontend/issues/579

I'm unable to do anything with my TRON due to my entire balance being frozen(?) and Tronscan says I have ZERO TRON Power. My account page has no visible Votes or method for unfreezing my tron.

**Comment by Manuel-Manuel** [comment]
My account got 30 TRX deleted into thin air with no tracking information (transaction) related to after freezing so my current state is that I have more tron power than my actual total balance (because my TRX were deleted without any cause). The whole system is buggy.

**Comment by JWhiteUX** [comment]
I'm gonna be pissed if I lost all of my TRX because of this wallet. I mean PISSED

**Comment by Manuel-Manuel** [comment]
We can do everything we want. The problems are the same: you don't know who to start from and where to point the issue since this is an online business, and most likely you would file for scam and fraud. Noone cares in this case. The other side could rebut easily but most importantly: we all knew the risk, and we all knew this could be just another ponzi scheme as there are many others. A lawsuit would be nice though.
