### ISSUE TITLE
Unable to unfreeze TRX tokens

### ISSUE THREAD

**Issue by pukkert** [tronscan/tronscan-frontend#851]
Hi i'm using Tronscan on a Mac (10.14.1). I never had issues before, but now I'm unable to unfreeze my tokens. I bought new TRX tokens last saturday night and frooze them immediately to gain more TRX by voting. Since then I had problems voting and receiving the appropriate amount of TRX for voting. Yesterday to freeze period should have ended, but now I can't unfreeze the tokens anymore. Please help, I'm missing out on TRX this way, but worse I'm not able to trade my TRX!

**Comment by LeeStewie** [comment]
I'm in the same boat.. any advice on this would be greatly appreciated!

**Comment by derscharni** [comment]
Same Bug in the webversion of tronscan

**Comment by wuno** [comment]
@pukkert did you ever get them to unfreeze? I have found 2 bugs,

Using the https://tronscan.github.io/tronscan-frontend app there seems to be bugs with voting after accessing my account with the Ledger. 

1. When existing votes are cast for a SR and I try to move them, the Ledger is not requested for signature. I realized after playing with it for a while that I had to leave 1 TRX in the original SR that I had casted my votes for in order to move my votes to the new SR and sign the transaction. Now when I try to remove the 1 TRX that is left on the original SR to any other SR then sign the transaction, it will not request signature on my Ledger. Instead it simply shows a loading gif continuously. 

2. When I try and unfreeze my tokens the modal appears and asks me if I would like to unfreeze, I select yes and the modal immediately closes without any other request for my interaction. The TRX remains frozen in my account.

**Comment by regnert** [comment]
cant unfreeze my trx today, release date was December 24, 2018. Maybe it isn't recognizing the year? Hope I don't have to wait until December 2019!

**Comment by wuno** [comment]
I have had this problem for a few weeks. 

I have pulled the code from the branch I think he created the website from. I ordered a few extra Ledgers to use for testing purposes and they come in the mail Friday. I reached out to the person who made the PR on Discord and Twitter but he has not been communicating very often. 

If anyone else would like to work with me to solve this issue once and for all please let me know.

**Comment by regnert** [comment]
thanks to anyone that can solve it. Sucks sitting on so many frozen knowing
they are useless.

**Comment by regnert** [comment]
finally worked ... only took 6 hours ... lol ... if someone fixed it thank
you so much! kiss kiss

**Comment by MiguelPachecoEOS** [comment]
@regnert how did you fix it?  :)

**Comment by regnert** [comment]
unfreezing the tokens finally worked after about 12 hours. Tronscan still
isnt updating any tokens though ... workaround is using tronlink plugin to
see/send

**Comment by wongzhunhou** [comment]
Please help, i face the same problem too. I am unable to unfreeze it despite waiting for over 3 days on tronscan.org
